#+title: Valencia Codes Katas
#+author: José Miguel
#+startup: showall

* Overview

 From [[https://en.wikipedia.org/wiki/Kata][Wikipedia]]:

 #+begin_quote
Kata is a Japanese word (型 or 形) meaning "form". It refers to a detailed
choreographed pattern of martial arts movements made to be practised alone.
 #+end_quote

 With these katas we aim to provide a set of exercises to learn tools and
 techniques for those who want to cut their teeth on programming.

 You can practise how to set up a project from scratch to code on your software
 language of choice, or to experiment with [[https://en.wikipedia.org/wiki/Test-driven_development][Test Driven Development]] using
 different libraries, or just jump to the Katas section for further ideas.

* About us

[[https://www.meetup.com/valencia-codes/][Valencia Codes]] is a community of technology enthusiasts meeting frequently
in Valencia, you can see our events on our [[https://www.meetup.com/valencia-codes/events/][meetup page]].

* Setup

** Common

- A shell, like bash, zsh, fish, etc to work with files and directories.
- An editor, vi, emacs, nano, etc to code your programs.
- Version Control System, you will be saved with git.

** Python

Make sure [[https://www.python.org/][Python]] is available:

#+begin_src sh :exports both :results code
python --version
#+end_src

#+RESULTS:
#+begin_src sh
Python 3.11.3
#+end_src

and then create a virtual environment to sandbox all your work.

#+begin_example
python -m venv .venv
#+end_example

#+begin_quote
Alternatively you can explore [[https://direnv.net/][direnv]] if you fancy it, just place a file named '.envrc' with the following content and direnv will do the magic every time you cd into the directory that contains that file.'
#+end_quote

#+begin_example
// .envrc
layout python3
#+end_example

For test driven development consider the following libraries:

- [[https://docs.python.org/3/library/unittest.html][unittest]]
- [[https://docs.pytest.org/en/7.3.x/][pytest]]

** NodeJS

Check [[https://nodejs.org/en][NodeJS]] is installed on your system:

#+begin_src sh :exports both :results code
node --version
#+end_src

#+RESULTS:
#+begin_src sh
v18.16.0
#+end_src

* Katas

- https://kata-log.rocks/tdd
- https://www.codewars.com/collections/tdd-katas
